apiVersion: v1
kind: Service
metadata:
  name: fastify-micro-smoke
  labels:
    app: fastify-micro-smoke
spec:
  selector:
    app: fastify-micro-smoke
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
